### ISSUE TITLE
Define namespace for vsso-core / vsso

### ISSUE THREAD

**Issue by danielwilms** [w3c/vsso#17]
We would have to define the namespace for:
* vsso-core
* vsso (generated triples)

@tguild: could you help with that?

**Comment by rtroncy** [comment]
What will be the difference between vsso and vsso-core? Both namespaces host vocabulary terms definitions and triples ultimately.

**Comment by danielwilms** [comment]
I was thinking, that we have a stable core and generated triples from vss, which updates with the speed of VSS and follows VSS versioning. I think it could be could to show this explicitly. What do you think @rtroncy?

**Comment by danielwilms** [comment]
@rtroncy, split I would see as following:

* Core: concepts, which reflect the _structure_ of VSS (VehicleComponent, VehicleProperty, etc.), basically everything you find [here](https://github.com/w3c/vsso/blob/main/vsso-core/vsso-core.ttl)
* vsso: concepts generated from vss, (mostly) subclassing `vsso-core`, eg. VIN, Brand, Speed, etc.

Core stays (more) stable, vsso gets generated with every version and will always 'live'

**Comment by rtroncy** [comment]
Does really vss change so often? Without any proper snapshot / versioning mechanism in place?
I find that doubling the number of namespaces is an obstacle for data consumers since any user of vsso would need to always embark the 2 namespaces.

**Comment by tguild** [comment]
I apparently didn't register vsso as a namespace when Raphael made the Member Submission, probably as that would be too early.

@caribouW3 can we have these namespaces before FPWD (now targeting January)

https://www.w3.org/ns/vsso and https://www.w3.org/ns/vsso-core

@danielwilms what can be at a namespace URI can vary, it could be a simple placeholder HTML document with links to resources, fuller html document, ttl, rdfs and other alternatives that get served via content negotiation. I prefer a human readable document with links to resources but that is a personal preference. Content negotiation can cause some confusion.

**Comment by caribouW3** [comment]
@tguild yes, I can set those up even without meaningful content to start with.

**Comment by rtroncy** [comment]
+1 for a HTML document behind these URLs that would point out to the machine readable representation (ttl, jsonld, etc.).

I'm still asking why do we need 2 namespaces though.

**Comment by danielwilms** [comment]
> Does really vss change so often? Without any proper snapshot / versioning mechanism in place?

VSS has proper versioning behind it and is released in the ideal case up to 4 times per year. I see that VSS focuses on the `VehiclePropery` while others can define `VehicleComponent` in more details. We have the case for example defining concepts for traceability, where you want to get the bill of materials for a certain `VehicleComponent`. In this case all you need for that is a stable vsso-core.

> I find that doubling the number of namespaces is an obstacle for data consumers since any user of vsso would need to always embark the 2 namespaces.

I relate to that argument. Maybe we can start with two documents under one namespace for the ontology and then see if a separation is useful. What do you think @rtroncy? @felixloesch, @tguild any opinion on that?

**Comment by felix-loesch** [comment]
I have the following comments:

1. I agree that splitting VSSo into 2 namespaces makes sense to separate the definition of core concepts from the actual VSS content, i.e. concrete signal and component definitions.
 "vsso-core": for core concepts (e.g. VehicleComponent, StaticVehicleProperty, DynamicVehicleProperty, ....)
 "vss": for the content coming from VSS (e.g. concrete properties
2. Regarding the "vss" namespace we should also include the VSS version number to differentiate different VSS versions. This is needed to prevent naming clashes between different VSS versions in VSSo.

**Comment by rtroncy** [comment]
@danielwilms moving terms from one namespace to another could also bring confusion for future data consumers so I would rather think carefully now what we imagine.

If applications making use of the sole envisioned `vsso-core` (e.g. for billing certain `VehicleComponent` components) will exist, then this justifies the separation of the ontology in two different namespaces and we could follow your original idea.

A few caveats:

- You're saying that VSS is updated 4 times a year ... but what type of updates is proposed? I assume rather monotonic ones, such as the new terms being added, maybe some being renamed but no profound changes in the structure, correct?
- OWL has `owl:versionInfo` and `owl:priorVersion` as Annotation Properties to indicate which version of the ontology a user agent is consuming. Similarly, for each ontology class and property, annotation properties can be used to explain from which version this term has been introduced, changed, etc. @felix-loesch I would not built in a version number in the namespace! This would be a killer for data consumers. A data consumer should have a permanent namespace to use (and dereference) and what it gets should indicate with metadata what terms are defined from which versions, etc.

**Comment by danielwilms** [comment]
> @danielwilms moving terms from one namespace to another could also bring confusion for future data consumers so I would rather think carefully now what we imagine.

I think you're right here. 

> If applications making use of the sole envisioned vsso-core (e.g. for billing certain VehicleComponent components) will exist, then this justifies the separation of the ontology in two different namespaces and we could follow your original idea.

That's what I see now, when using it internally that this is a valid use case. I think it could be beneficial that way.

> You're saying that VSS is updated 4 times a year ... but what type of updates is proposed? I assume rather monotonic ones, such as the new terms being added, maybe some being renamed but no profound changes in the structure, correct?

Correct. As a consequence the `vsso-core` wouldn't be touched.

> OWL has owl:versionInfo and owl:priorVersion as Annotation Properties to indicate which version of the ontology a user agent is consuming. 

Fully agree here.
