### ISSUE TITLE
workshop preparation

### ISSUE THREAD

**Issue by danielwilms** [w3c/vsso#26]
Date: 14.03.22
Time: 4pm - 7pm CET

Agenda:
- Current status @danielwilms 
- #22 @felix-loesch
- #13 
- #9
- Next steps, tooling & todos

**Comment by tguild** [comment]
agenda+ Core truth and workflow (could be subtopic of next steps and tooling)

**Comment by danielwilms** [comment]
* Documentation on 
  * how to extend signals/core ontology.
  * how to use observations (more detailed than use cases)
* @tguild sets up doodle for special working group call
* Punning as possible way out of subclass vs instances
* @danielwilms create tooling PR for subclasses/instances

**Comment by tguild** [comment]
https://www.w3.org/2022/03/14-auto-minutes minutes from yesterday, will include links to video recording and slides after receiving
