### ISSUE TITLE
doc: all VSSo links in README.md Quick Start are broken

### ISSUE THREAD

**Issue by slawr** [w3c/vsso#35]
Hi all of the VSSo links in the README.md Quick Start result in 404 errors, e.g. https://github.com/w3c/vsso/blob/gh-pages/vsso-primer

Playing with URLs didn't make clear what the correct links should be so I've raised an issue rather than send a PR.

**Comment by danielwilms** [comment]
Hi @slawr, thanks for the pointer. Fixed it.
