### ISSUE TITLE
Create WebProtege Project to explore

### ISSUE THREAD

**Issue by danielwilms** [w3c/vsso#7]
I think that would be helpful to check the current state and work on improvements.

**Comment by rtroncy** [comment]
While sharing a WebProtege project may be handy, I think we should not require it as anyone could use his favorite ontology editor, being TopBraid or something else. What is important is that the ontology is properly versioned in the github repository with an adequate process to manage change requests

**Comment by danielwilms** [comment]
@rtroncy, sorry wasn't clear enough. Didn't mean that the work should be done there, but just having a quick way of exploring and understanding. But I see as well that it might add a complexity of keeping it up to date. Maybe we don't necessarily need it.

**Comment by danielwilms** [comment]
I think documentation as html page with vowl should be enough
